/* ======================================================
   Simulasi Banjir — Player Monitor v3 (Supabase)
   ====================================================== */
const $=s=>document.querySelector(s),$$=s=>document.querySelectorAll(s);
const SB='https://qbxvttgzxlfjockyrxne.supabase.co/rest/v1';
const SK='eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFieHZ0dGd6eGxmam9ja3lyeG5lIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODI1MjczNzAsImV4cCI6MjA5ODEwMzM3MH0.GiQcsITIxZbCaDn6746Wds-0Cf5IbwH7_xFDtWe5HW0';
const H={apikey:SK,Authorization:'Bearer '+SK};
async function F(e){try{const r=await fetch(SB+e,{headers:H});return r.ok?await r.json():[]}catch(e){return[]}}

const S={tab:'behavior',raw:{behavior:[],gui:[],npc:[]},fil:[],ap:[],sp:'',dl:'',et:'',sr:'',p:1,rpp:50,sc:null,sd:'asc',ri:10,rt:null,ls:0};
const M={behavior:{fk:'behavior_sequence'},gui:{fk:'ui_element'},npc:{fk:'npc_name'},overview:{fk:null}};

async function init(){tick();setInterval(tick,1e3);await load();disc();fsetup();tsetup();ssetup();esetup();rsetup();ltimer();sw('behavior')}
function tick(){const n=new Date();if($('#currentDate'))$('#currentDate').textContent=n.toLocaleDateString('id-ID',{weekday:'short',year:'numeric',month:'short',day:'numeric',hour:'2-digit',minute:'2-digit'});if($('#footerUpdate'))$('#footerUpdate').textContent='🕐 '+n.toLocaleTimeString('id-ID')}

async function load(){try{const[b,n,g]=await Promise.all([F('/behavior_logs?select=*&order=created_at.desc&limit=5000'),F('/npc_interactions?select=*&order=created_at.desc&limit=2000'),F('/gui_logs?select=*&order=created_at.desc&limit=2000')]);S.raw.behavior=b||[];S.raw.npc=n||[];S.raw.gui=g||[];console.log('✅',S.raw.behavior.length,'b |',S.raw.npc.length,'n |',S.raw.gui.length,'g');}catch(e){}}
function disc(){const m=new Map();for(const t of['behavior','gui','npc'])for(const r of S.raw[t]){if(!r.player_id)continue;if(!m.has(r.player_id))m.set(r.player_id,{id:r.player_id,name:r.player_name||'?',ts:r.created_at||''});const p=m.get(r.player_id);if(r.created_at&&r.created_at>p.ts)p.ts=r.created_at;}S.ap=[...m.values()].sort((a,b)=>b.ts.localeCompare(a.ts));}

function fsetup(){const s=$('#playerFilter');s.innerHTML='<option value="">Semua Player</option>'+S.ap.map(p=>'<option value="'+escA(p.name)+'">'+escH(p.name)+'</option>').join('');s.addEventListener('change',()=>{S.sp=s.value;});$('#dateLive').addEventListener('change',()=>{S.dl=$('#dateLive').value;});const d=new Date().toISOString().slice(0,10);$('#dateLive').value=d;S.dl=d;$('#applyFiltersBtn').addEventListener('click',()=>{S.sp=$('#playerFilter').value;S.dl=$('#dateLive').value;S.p=1;apply();});$('#resetFiltersBtn').addEventListener('click',()=>{$('#playerFilter').value='';S.sp='';S.dl=new Date().toISOString().slice(0,10);$('#dateLive').value=S.dl;S.et='';S.sr='';$('#searchInput').value='';S.p=1;apply();});}
function tsetup(){$$('.tab').forEach(b=>b.addEventListener('click',()=>sw(b.dataset.tab)));}
function sw(t){S.tab=t;S.p=1;S.et='';$$('.tab').forEach(b=>b.classList.remove('active'));const btn=document.querySelector('.tab[data-tab="'+t+'"]');if(btn)btn.classList.add('active');$$('.tab-view').forEach(v=>v.classList.remove('active'));const dv=document.getElementById('view-'+t);if(dv)dv.classList.add('active');updET();apply();}
function ssetup(){$('#searchInput').addEventListener('input',deb(e=>{S.sr=e.target.value.toLowerCase();S.p=1;apply();},250));}
$('#filterType').addEventListener('change',e=>{S.et=e.target.value;S.p=1;apply();});
function updET(){if(S.tab==='overview'||S.tab==='npc')return;const d=grd();const s=$('#filterType');s.innerHTML='<option value="">Semua</option>';const k=M[S.tab]?.fk;if(!k)return;[...new Set(d.map(r=>Array.isArray(r[k])?r[k][0]:r[k]).filter(Boolean))].sort().forEach(v=>{const o=document.createElement('option');o.value=v;o.textContent=String(v).slice(0,40);s.appendChild(o);});}
function rsetup(){$('#refreshInterval').addEventListener('change',e=>{S.ri=parseInt(e.target.value);clearInterval(S.rt);if(S.ri>0)S.rt=setInterval(ref,5e3);});if(S.ri>0)S.rt=setInterval(ref,5e3);}
async function ref(){await load();disc();apply();rnote();}
function rnote(){const n=new Date(),note='🔄 '+n.toLocaleTimeString('id-ID');['refreshNote','refreshNoteGui'].forEach(id=>{const e=document.getElementById(id);if(e)e.textContent=note;});if($('#footerUpdate'))$('#footerUpdate').textContent=n.toLocaleTimeString('id-ID');}
function ltimer(){setInterval(()=>{S.ls++;const m=Math.floor(S.ls/60),s=S.ls%60;if($('#liveTimer'))$('#liveTimer').textContent=String(m).padStart(2,'0')+':'+String(s).padStart(2,'0');},1e3);}

function grd(){if(S.tab==='overview'||S.tab==='npc')return[];return S.raw[S.tab]||[];}
function apply(){if(S.tab==='overview'){S.fil=[];rall();return;}if(S.tab==='npc'){rall();return;}let d=[...grd()];if(S.sp)d=d.filter(r=>r.player_name===S.sp);if(S.dl)d=d.filter(r=>r.created_at&&r.created_at.slice(0,10)===S.dl);if(S.et){const k=M[S.tab]?.fk;if(k)d=d.filter(r=>{const v=r[k];return Array.isArray(v)?v[0]===S.et:v===S.et;});}if(S.sr)d=d.filter(r=>Object.values(r).some(v=>v!=null&&String(v).toLowerCase().includes(S.sr)));S.fil=d;rall();}
function sb(c){if(S.sc===c)S.sd=S.sd==='asc'?'desc':'asc';else{S.sc=c;S.sd='asc';}apply();}

function rall(){ustats();ubadge();rnote();if(S.tab==='overview')rov();else if(S.tab==='npc')rnpc();else rtab();dmap();}
function ustats(){$('#statChats').textContent=(S.raw.npc||[]).length;$('#statMoves').textContent=(S.raw.behavior||[]).length;$('#statGui').textContent=(S.raw.gui||[]).length;$('#statPlayers').textContent=S.ap.length;}
function ubadge(){if($('#playerCountBadge'))$('#playerCountBadge').textContent=S.ap.length+' Pemain';}

function rtab(){const m={behavior:{tid:'dataTable',hid:'tableHead',bid:'tableBody',rid:'rowsShown',pid:'pagination'},gui:{tid:'dataTableGui',hid:'tableHeadGui',bid:'tableBodyGui',rid:'rowsShownGui',pid:'paginationGui'}}[S.tab];if(!m)return;const f=S.fil,st=(S.p-1)*S.rpp,en=Math.min(st+S.rpp,f.length),pd=f.slice(st,en);if(!f.length){document.getElementById(m.hid).innerHTML='';document.getElementById(m.bid).innerHTML='<tr><td colspan="99" class="empty-state">📭 Tidak ada data</td></tr>';document.getElementById(m.rid).textContent='Menampilkan 0 dari 0';document.getElementById(m.pid).innerHTML='';return;}
const cols=(S.tab==='behavior'?['created_at','player_name','position_history','behavior_sequence']:Object.keys(f[0]).filter(c=>c!=='id'&&c!=='player_id'&&c!=='player_nickname'&&c!=='mouse_events'&&c!=='session_time'&&!c.startsWith('_')));
document.getElementById(m.hid).innerHTML='<tr>'+cols.map(c=>'<th onclick="sb(\''+c+'\')">'+fhdr(c)+'<span class="sort-arrow">'+(S.sc===c?(S.sd==='asc'?'▲':'▼'):'')+'</span></th>').join('')+'</tr>';
document.getElementById(m.bid).innerHTML=pd.map(r=>'<tr>'+cols.map(c=>'<td title="'+escA(String(r[c]??''))+'">'+fcell(c,r[c])+'</td>').join('')+'</tr>').join('');
document.getElementById(m.rid).textContent='Menampilkan '+(st+1)+'–'+en+' dari '+f.length.toLocaleString();
const tp=Math.ceil(f.length/S.rpp),pe=document.getElementById(m.pid);if(tp<=1)pe.innerHTML='';else{let h='<button class="page-btn"'+(S.p<=1?' disabled':'')+' onclick="gp('+(S.p-1)+')">‹</button>';for(let i=1;i<=tp;i++)h+='<button class="page-btn'+(i===S.p?' active':'')+'" onclick="gp('+i+')">'+i+'</button>';h+='<button class="page-btn"'+(S.p>=tp?' disabled':'')+' onclick="gp('+(S.p+1)+')">›</button>';pe.innerHTML=h;}}
function gp(p){S.p=p;apply();}
function rnpc(){let c=[...S.raw.npc].reverse();if(S.sp)c=c.filter(r=>r.player_name===S.sp);if(S.dl)c=c.filter(r=>r.created_at&&r.created_at.slice(0,10)===S.dl);if(S.sr)c=c.filter(r=>Object.values(r).some(v=>v!=null&&String(v).toLowerCase().includes(S.sr)));const box=$('#chatLogBox');if(!box)return;if(!c.length){box.innerHTML='<div class="empty-state">💬 Belum ada percakapan NPC</div>';return;}const st=(S.p-1)*S.rpp,en=Math.min(st+S.rpp,c.length);box.innerHTML=c.slice(st,en).map(r=>{const t=r.created_at?new Date(r.created_at).toLocaleTimeString('id-ID'):'';return'<div class="chat-bubble player"><div class="npc-label">🤖 '+escH(r.npc_name||'NPC')+'</div><div class="sender">'+escH(r.player_name||'Player')+'</div><div>'+escH(r.message||'')+'</div><div class="time">'+t+'</div></div>';}).join('');box.scrollTop=box.scrollHeight;if($('#rowsShownNpc'))$('#rowsShownNpc').textContent='Menampilkan '+(st+1)+'–'+en+' dari '+c.length.toLocaleString();}
function rov(){const pl={};for(const r of[...S.raw.behavior,...S.raw.npc,...S.raw.gui]){const n=r.player_name||'?';if(!pl[n])pl[n]={name:n,chats:0,moves:0,guis:0};if(r.npc_name)pl[n].chats++;else if(r.position_history)pl[n].moves++;else pl[n].guis++;}const ps=Object.values(pl).sort((a,b)=>(b.chats+b.moves+b.guis)-(a.chats+a.moves+a.guis));if($('#playerListPanel'))$('#playerListPanel').innerHTML=ps.length?ps.slice(0,15).map(p=>'<div class="player-item" onclick="fbp(\''+escA(p.name)+'\')"><span class="player-name">👤 '+escH(p.name)+'</span><span class="player-count-badge-sm">'+(p.chats+p.moves+p.guis)+'</span></div>').join(''):'<div class="empty-state" style="padding:20px">Belum ada pemain</div>';const nc={};for(const r of S.raw.npc){if(r.npc_name)nc[r.npc_name]=(nc[r.npc_name]||0)+1;}const ns=Object.entries(nc).sort((a,b)=>b[1]-a[1]);if($('#npcListPanel'))$('#npcListPanel').innerHTML=ns.length?ns.slice(0,15).map(([n,c])=>'<div class="npc-item"><span>🤖 '+escH(n)+'</span><span class="npc-count-badge">'+c+' chat</span></div>').join(''):'<div class="empty-state" style="padding:20px">Belum ada interaksi</div>';dchart();}

// Chart
function dchart(){const cv=$('#activityChart');if(!cv)return;const ctx=cv.getContext('2d'),w=cv.parentElement.clientWidth-28;cv.width=w;cv.height=250;ctx.clearRect(0,0,cv.width,cv.height);const bk={};for(const r of[...S.raw.behavior,...S.raw.npc,...S.raw.gui]){if(!r.created_at)continue;const t=r.created_at.slice(0,16);if(!bk[t])bk[t]={b:0,n:0,g:0};if(r.position_history)bk[t].b++;else if(r.npc_name)bk[t].n++;else bk[t].g++;}const ks=Object.keys(bk).sort();if(ks.length<2){ctx.fillStyle='#8b8fa3';ctx.font='13px system-ui';ctx.textAlign='center';ctx.fillText('📈 Butuh data',cv.width/2,cv.height/2);return;}const pad=40,pw=cv.width-pad*2,ph=cv.height-pad*2,mx=Math.max(1,...ks.map(k=>bk[k].b+bk[k].n+bk[k].g));ctx.strokeStyle='#2e3242';ctx.lineWidth=0.5;for(let i=0;i<=4;i++){const y=pad+ph*(1-i/4);ctx.beginPath();ctx.moveTo(pad,y);ctx.lineTo(cv.width-pad,y);ctx.stroke();}const bw=Math.max(2,Math.min(12,pw/ks.length-2));ks.forEach((k,i)=>{const x=pad+i*(pw/ks.length)+bw/2,b=bk[k];ctx.fillStyle='#5865f2';ctx.fillRect(x,pad+ph-(b.b/mx)*ph,bw,(b.b/mx)*ph);ctx.fillStyle='#f59e0b';ctx.fillRect(x,pad+ph-((b.b+b.n)/mx)*ph,bw,(b.n/mx)*ph);ctx.fillStyle='#06b6d4';ctx.fillRect(x,pad+ph-((b.b+b.n+b.g)/mx)*ph,bw,(b.g/mx)*ph);});ks.forEach((k,i)=>{if(i%Math.ceil(ks.length/8)===0||i===ks.length-1){ctx.fillStyle='#8b8fa3';ctx.font='9px monospace';ctx.textAlign='center';ctx.fillText(k.slice(11,16),pad+i*(pw/ks.length)+bw/2,cv.height-8);}});ctx.fillStyle='#5865f2';ctx.fillRect(pad+10,10,10,10);ctx.fillStyle='#e1e4ed';ctx.font='11px system-ui';ctx.textAlign='left';ctx.fillText('Behavior',pad+24,20);ctx.fillStyle='#f59e0b';ctx.fillRect(pad+100,10,10,10);ctx.fillText('NPC Chat',pad+114,20);ctx.fillStyle='#06b6d4';ctx.fillRect(pad+190,10,10,10);ctx.fillText('GUI',pad+204,20);}

// Minimap
function dmap(){const cv=$('#minimapCanvas');if(!cv)return;const ctx=cv.getContext('2d'),sz=280;cv.width=sz;cv.height=sz;ctx.fillStyle='#121520';ctx.fillRect(0,0,sz,sz);ctx.strokeStyle='#1e2438';ctx.lineWidth=0.5;for(let i=0;i<=sz;i+=sz/10){ctx.beginPath();ctx.moveTo(i,0);ctx.lineTo(i,sz);ctx.stroke();ctx.beginPath();ctx.moveTo(0,i);ctx.lineTo(sz,i);ctx.stroke();}
const pos={};const nw=new Date();
for(const r of(S.raw.behavior||[])){const ph=r.position_history;if(!ph||!ph.length)continue;const lp=ph[ph.length-1];if(lp.x==null||lp.y==null)continue;const nm=r.player_name||'?';if(!pos[nm]||(r.created_at>pos[nm].ts))pos[nm]={x:parseFloat(lp.x),y:parseFloat(lp.y),ts:r.created_at};}
const es=Object.entries(pos);
if(!es.length){ctx.fillStyle='#8b8fa3';ctx.font='13px system-ui';ctx.textAlign='center';ctx.fillText('🗺️ Menunggu data',sz/2,sz/2);rpl();return;}
let mnX=Infinity,mnY=Infinity,mxX=-Infinity,mxY=-Infinity;for(const[,p]of es){mnX=Math.min(mnX,p.x);mnY=Math.min(mnY,p.y);mxX=Math.max(mxX,p.x);mxY=Math.max(mxY,p.y);}
const pd=30,rX=mxX-mnX||50,rY=mxY-mnY||50,sc=Math.min((sz-pd*2)/rX,(sz-pd*2)/rY),ox=(sz-(rX*sc))/2-mnX*sc,oy=(sz-(rY*sc))/2-mnY*sc;
for(const[nm,p]of es){const px=p.x*sc+ox,py=sz-(p.y*sc+oy);if(px<0||px>sz||py<0||py>sz)continue;const ag=(nw-new Date(p.ts))/6e4;let cl='#22c55e',gl='rgba(34,197,94,.6)',r=5;if(ag>15){cl='#8b8fa3';gl='rgba(139,143,163,.3)';r=3;}else if(ag>5){cl='#f59e0b';gl='rgba(245,158,11,.4)';r=4;}ctx.fillStyle=gl;ctx.beginPath();ctx.arc(px,py,r+3,0,Math.PI*2);ctx.fill();ctx.fillStyle=cl;ctx.beginPath();ctx.arc(px,py,r,0,Math.PI*2);ctx.fill();ctx.fillStyle='#e1e4ed';ctx.font='9px system-ui';ctx.textAlign='center';ctx.fillText(nm.slice(0,10),px,py-10);}
rpl();}
function rpl(){const c=$('#playerList');if(!c)return;c.innerHTML=S.ap.length?S.ap.slice(0,20).map(p=>{const ch=S.raw.npc.filter(r=>r.player_name===p.name).length,mv=S.raw.behavior.filter(r=>r.player_name===p.name).length,gu=S.raw.gui.filter(r=>r.player_name===p.name).length;return'<div class="player-item" onclick="fbp(\''+escA(p.name)+'\')"><span class="player-name">👤 '+escH(p.name)+'</span><span class="player-count-badge-sm">'+(ch+mv+gu)+'</span></div>';}).join(''):'<div class="empty-state" style="padding:15px">Belum ada pemain</div>';}
function fbp(n){const s=$('#playerFilter');if(s){s.value=n;S.sp=n;}S.p=1;apply();}

function esetup(){$('#exportCSV')?.addEventListener('click',exCSV);$('#exportJSON')?.addEventListener('click',exJSON);$('#rowsPerPage')?.addEventListener('change',e=>{S.rpp=parseInt(e.target.value);S.p=1;apply();});}
function exCSV(){if(S.tab==='npc')return;const d=grd();if(!d.length)return;const cs=S.tab==='behavior'?['created_at','player_name','position_history','behavior_sequence']:Object.keys(d[0]).filter(c=>c!=='id');dl('export_'+S.tab+'.csv',cs.join(',')+'\n'+d.map(r=>cs.map(c=>'"'+String(r[c]||'').replace(/"/g,'""')+'"').join(',')).join('\n'),'text/csv');}
function exJSON(){const d=S.tab==='npc'?S.raw.npc:grd();dl('export_'+S.tab+'.json',JSON.stringify(d,null,2),'application/json');}
function dl(n,c,t){const b=new Blob([c],{type:t}),u=URL.createObjectURL(b),a=document.createElement('a');a.href=u;a.download=n;a.click();URL.revokeObjectURL(u);}

function fhdr(c){return c.replace(/_/g,' ').replace(/\b\w/g,l=>l.toUpperCase());}
function fcell(c,v){if(v==null)return'—';if(c==='created_at')try{return new Date(v).toLocaleString('id-ID');}catch(e){return String(v);}if(c==='position_history'&&Array.isArray(v)&&v.length){const p=v[v.length-1];return'('+Math.round(p.x)+', '+Math.round(p.y)+')';}if(Array.isArray(v))return v[0]||'';if(typeof v==='object')return JSON.stringify(v).slice(0,50);return String(v).slice(0,100);}

function deb(fn,ms){let t;return function(...args){clearTimeout(t);t=setTimeout(()=>fn.apply(this,args),ms);};}
function escH(s){return String(s).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;');}
function escA(s){return String(s).replace(/&/g,'&amp;').replace(/"/g,'&quot;').replace(/</g,'&lt;').replace(/>/g,'&gt;');}
init();
